run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - staticcheck   # Static analysis
    - gosimple      # Simplify code
    - unused        # Check for unused code
    - goconst       # Find repeated strings that could be constants
    - misspell      # Find commonly misspelled words
    - gocyclo       # Check cyclomatic complexity
    - gofmt         # Check formatting
    - ineffassign   # Detect ineffectual assignments
    - gosec         # Security checks
  disable:
    - typecheck     # Disabled: has false positives with external modules

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Disabled: too many structural optimization issues

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  gosec:
    excludes:
      - G204  # Allow subprocess launching (we need this for git commands)
      - G304  # Allow file path from variable (we validate these)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  # Start with warnings only, will enforce in Phase 2
  new: false

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec

    # Exclude long lines for generated code or comments
    - linters:
        - lll
      source: "^//go:generate "

    # Exclude typecheck errors from external modules
    - path: "pkg/mod/"
      linters:
        - typecheck

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
